import type { Product } from "./types.js";

export const products: Product[] = [
    {
        id: 1,
        name: "Wireless Earbuds Pro",
        description: "Noise-cancelling earbuds with a 30-hour charging case.",
        category: "electronics",
        price: { amount: 899000, originalAmount: 1199000 },
        stock: { kind: "in-stock", quantity: 48 },
        badge: "sale",
        tags: ["audio", "bluetooth", "wireless"],
    },
    {
        id: 2,
        name: "Batik Cotton Shirt",
        description: "Hand-stamped batik pattern on breathable cotton.",
        category: "clothing",
        price: { amount: 275000 },
        stock: { kind: "low-stock", quantity: 3 },
        badge: "bestseller",
        tags: ["batik", "shirt", "cotton"],
    },
    {
        id: 3,
        name: "Ceramic Pour-Over Set",
        description: "Dripper, server and two cups for slow morning coffee.",
        category: "home",
        price: { amount: 345000 },
        stock: { kind: "in-stock", quantity: 20 },
        badge: "new",
        tags: ["coffee", "kitchen", "ceramic"],
    },
    {
        id: 4,
        name: "Learning TypeScript",
        description: "A practical guide to types for JavaScript developers.",
        category: "books",
        price: { amount: 189000 },
        stock: { kind: "in-stock", quantity: 35 },
        badge: null,
        tags: ["programming", "typescript", "book"],
    },
    {
        id: 5,
        name: "Mechanical Keyboard 75%",
        description: "Hot-swappable switches, aluminium case, USB-C.",
        category: "electronics",
        price: { amount: 1350000 },
        stock: { kind: "out-of-stock", restockDate: "2026-10-15" },
        badge: null,
        tags: ["keyboard", "mechanical", "usb-c"],
    },
    {
        id: 6,
        name: "Linen Throw Pillow",
        description: "Washed linen cover with a feather-blend insert.",
        category: "home",
        price: { amount: 159000, originalAmount: 219000 },
        stock: { kind: "low-stock", quantity: 2 },
        badge: "sale",
        tags: ["decor", "linen", "pillow"],
    },
];